
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PlantsTable
{
    private readonly System.Collections.Generic.Dictionary<PlantsEnum, PlantsConfig> _dataMap;
    private readonly System.Collections.Generic.List<PlantsConfig> _dataList;
    
    public PlantsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<PlantsEnum, PlantsConfig>();
        _dataList = new System.Collections.Generic.List<PlantsConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlantsConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PlantsConfig.DeserializePlantsConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<PlantsEnum, PlantsConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PlantsConfig> DataList => _dataList;

    public PlantsConfig GetOrDefault(PlantsEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlantsConfig Get(PlantsEnum key) => _dataMap[key];
    public PlantsConfig this[PlantsEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

