
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PlantsConfig : Luban.BeanBase
{
    public PlantsConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (PlantsEnum)_buf["id"].AsInt; }
        { if(!_buf["localizationKey"].IsString) { throw new SerializationException(); }  LocalizationKey = _buf["localizationKey"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["stage_time_percents"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; StageTimePercents = new float[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  StageTimePercents[__index0++] = __v0; }   }
        { if(!_buf["total_time_second"].IsNumber) { throw new SerializationException(); }  TotalTimeSecond = _buf["total_time_second"]; }
    }

    public static PlantsConfig DeserializePlantsConfig(JSONNode _buf)
    {
        return new PlantsConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly PlantsEnum Id;
    /// <summary>
    /// 本地化Key
    /// </summary>
    public readonly string LocalizationKey;
    public readonly string Desc;
    /// <summary>
    /// 五个阶段生长时间占比
    /// </summary>
    public readonly float[] StageTimePercents;
    /// <summary>
    /// 从种子到死亡需要的总时间
    /// </summary>
    public readonly float TotalTimeSecond;
   
    public const int __ID__ = -883685142;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "localizationKey:" + LocalizationKey + ","
        + "desc:" + Desc + ","
        + "stageTimePercents:" + Luban.StringUtil.CollectionToString(StageTimePercents) + ","
        + "totalTimeSecond:" + TotalTimeSecond + ","
        + "}";
    }
}

}
